[phases.setup]
npx-version = "9.8.1"

[phases.setup.requires]
node = "18"

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node backend/src/index.js"

[build.args]
NODE_VERSION = "18"
