npx-version = "9.8.1"

[phases.setup.requires]
node = "18"

[phases.install]
cmds = [
    "npm install",
    "cd frontend && npm install --legacy-peer-deps",
    "cd ../backend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd ../backend && npm run build"
]

[start]
cmd = "node backend/src/index.js"

[build.args]
